# Generated by Django 5.2 on 2025-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
