# Generated by Django 5.2 on 2025-04-25 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Toyota', 'Toyota'), ('Mercedes', 'Mercedes'), ('Autre', 'Autre')], max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('chauffeur', models.OneToOneField(blank=True, limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
